#!/usr/bin/env python3
"""
=========================================================
 Audio Library Toolkit
---------------------------------------------------------
 Tool      : Auto Cutter
 Version   : 1.2.1
 Author    : Raymond Ummels
 License   : MIT
=========================================================

Reads silence_report.csv generated by Silence Scanner.

Creates trimmed COPIES of audio files.

Original files are NEVER modified.

Folder structure is preserved.

Workflow

Silence Scanner
        │
        ▼
silence_report.csv
        │
        ▼
Auto Cutter
        │
        ▼
Music_Cut
"""

import csv
import os
import subprocess
import sys
import time

from pathlib import Path

# =========================================================
# CONFIG
# =========================================================

VERSION = "1.2.0"

FFMPEG = r"C:\ffmpeg\ffmpeg.exe"
FFPROBE = r"C:\ffmpeg\ffprobe.exe"

CSV_FILE = "silence_report.csv"

OUTPUT_FOLDER = "Music_Cut"

BITRATE = "320k"

KEEP_START = 0.20
KEEP_END = 0.20

SHOW_FFMPEG = False

LINE = "=" * 58

# =========================================================
# Helper Functions
# =========================================================

def die(message):

    print()
    print(LINE)
    print("ERROR")
    print(LINE)
    print(message)
    print()
    sys.exit(1)


def file_exists(filename):

    return Path(filename).is_file()


def format_time(seconds):

    seconds = max(0, int(seconds))

    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60

    return f"{hours:02}:{minutes:02}:{secs:02}"


def print_header():

    print(LINE)
    print("Audio Library Toolkit")
    print(f"Auto Cutter v{VERSION}")
    print(LINE)
    print()

# =========================================================
# Startup Checks
# =========================================================

if not file_exists(FFMPEG):
    die(f"FFmpeg not found:\n{FFMPEG}")

if not file_exists(FFPROBE):
    die(f"FFprobe not found:\n{FFPROBE}")

if not file_exists(CSV_FILE):
    die(f"CSV not found:\n{CSV_FILE}")

# =========================================================
# Read CSV
# =========================================================

try:

    with open(
        CSV_FILE,
        newline="",
        encoding="utf-8-sig"
    ) as csvfile:

        rows = list(
            csv.DictReader(
                csvfile,
                delimiter=";"
            )
        )

except Exception as exc:

    die(str(exc))

if not rows:
    die("CSV is empty.")

# =========================================================
# Detect Music Root
# =========================================================

first_file = Path(rows[0]["File"])

music_root = first_file.parent.parent

output_root = music_root / OUTPUT_FOLDER

output_root.mkdir(
    parents=True,
    exist_ok=True
)

# =========================================================
# Runtime Variables
# =========================================================

start_time = time.time()

created = 0
skipped = 0
errors = 0

total_intro_removed = 0.0
total_outro_removed = 0.0

seen_files = set()

report = []

# =========================================================
# Startup Information
# =========================================================

print_header()

print(f"Files in CSV : {len(rows)}")
print(f"Music Root   : {music_root}")
print(f"Output Folder: {output_root}")
print()
# =========================================================
# Audio Helper Functions
# =========================================================

def get_duration(filename):
    """
    Returns the duration of an audio file in seconds.
    """

    cmd = [
        FFPROBE,
        "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(filename)
    ]

    result = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace"
    )

    if result.returncode != 0:
        return None

    try:
        return float(result.stdout.strip())

    except ValueError:
        return None


# =========================================================
# Calculate Cut Positions
# =========================================================

def calculate_times(row, duration):

    intro_cut = 0.0
    outro_cut = 0.0

    problem = row["Problem"].upper()

    if "LONG INTRO" in problem:

        intro_cut = max(
            0.0,
            float(row["Intro"]) - KEEP_START
        )

    if "BAD OUTRO" in problem:

        outro_cut = max(
            0.0,
            float(row["Outro"]) - KEEP_END
        )

    end_time = duration - outro_cut

    if end_time <= intro_cut:
        return None

    return (
        round(intro_cut, 3),
        round(end_time, 3)
    )


# =========================================================
# FFmpeg Cutter
# =========================================================

def cut_audio(
    source,
    destination,
    start_time,
    end_time
):

    cut_duration = end_time - start_time

    cmd = [

        FFMPEG,

        "-hide_banner",
        "-loglevel", "error",

        "-y",

        "-i", str(source),

        "-ss", f"{start_time:.3f}",
        "-t", f"{cut_duration:.3f}",

        "-map_metadata", "0",
        "-map", "0:a:0",

        "-c:a", "libmp3lame",
        "-b:a", BITRATE,

        str(destination)

    ]

    if SHOW_FFMPEG:
        print(" ".join(cmd))

    result = subprocess.run(cmd)

    if result.returncode != 0:
        return False

    if not destination.exists():
        return False

    if destination.stat().st_size == 0:
        return False

    return True


# =========================================================
# Progress Display
# =========================================================

def show_progress(
    index,
    total,
    filename,
    created,
    skipped,
    errors,
    start_time,
    status="CHECKING"
):

    os.system("cls")

    elapsed = time.time() - start_time

    percent = (index / total) * 100

    if index < 20:
        eta_text = "calculating..."
    else:
        average = elapsed / index
        eta = average * (total - index)
        eta_text = format_time(eta)

    print(LINE)
    print("Audio Library Toolkit")
    print(f"Auto Cutter v{VERSION}")
    print(LINE)
    print()

    print(f"Files       : {total}")
    print(f"Processed   : {index}/{total} ({percent:.1f}%)")
    print()

    print("Current File")
    print("-" * 58)
    print(filename)
    print()

    print(f"Status      : {status}")
    print()

    print(f"Created     : {created}")
    print(f"Skipped     : {skipped}")
    print(f"Errors      : {errors}")
    print()

    print(f"Elapsed     : {format_time(elapsed)}")
    print(f"ETA         : {eta_text}")
    print()

    print(LINE)
	# =========================================================
# Main Processing Loop
# =========================================================

for index, row in enumerate(rows, start=1):

    source = Path(row["File"])

    show_progress(
        index=index,
        total=len(rows),
        filename=source.name,
        created=created,
        skipped=skipped,
        errors=errors,
        start_time=start_time
    )

    # -----------------------------------------------------
    # Skip duplicate source
    # -----------------------------------------------------

    source_key = str(source).lower()

    if source_key in seen_files:

        report.append([
            source.name,
            "SKIPPED",
            "Duplicate source"
        ])

        skipped += 1
        continue

    seen_files.add(source_key)

    # -----------------------------------------------------
    # Source file exists
    # -----------------------------------------------------

    if not source.exists():

        report.append([
            source.name,
            "ERROR",
            "Source file missing"
        ])

        errors += 1
        continue

    # -----------------------------------------------------
    # Get duration
    # -----------------------------------------------------

    duration = get_duration(source)

    if duration is None:

        report.append([
            source.name,
            "ERROR",
            "Could not determine duration"
        ])

        errors += 1
        continue

    # -----------------------------------------------------
    # Calculate cut positions
    # -----------------------------------------------------

    cut = calculate_times(row, duration)

    if cut is None:

        report.append([
            source.name,
            "SKIPPED",
            "Nothing to cut"
        ])

        skipped += 1
        continue

    start_cut, end_cut = cut

    # -----------------------------------------------------
    # Preserve folder structure
    # -----------------------------------------------------

    relative_folder = source.parent.relative_to(
        music_root
    )

    destination_folder = (
        output_root / relative_folder
    )

    destination_folder.mkdir(
        parents=True,
        exist_ok=True
    )

    destination = (
        destination_folder / source.name
    )

    # -----------------------------------------------------
    # Resume support
    # -----------------------------------------------------

    if destination.exists():

        report.append([
            str(destination.relative_to(output_root)),
            "SKIPPED",
            "Already exists"
        ])

        skipped += 1
        continue

    # -----------------------------------------------------
    # Cut audio
    # -----------------------------------------------------

    success = cut_audio(
        source,
        destination,
        start_cut,
        end_cut
    )

    if success:

        created += 1

        intro_removed = start_cut
        outro_removed = duration - end_cut
        total_intro_removed += intro_removed
        total_outro_removed += outro_removed

        report.append([
            str(destination.relative_to(output_root)),
            "CREATED",
            f"Intro={intro_removed:.2f}s "
            f"Outro={outro_removed:.2f}s"
        ])

    else:

        errors += 1

        report.append([
            source.name,
            "ERROR",
            "FFmpeg failed"
        ])
		# =========================================================
# Write Report
# =========================================================

report_file = "cut_report.csv"

with open(
    report_file,
    "w",
    newline="",
    encoding="utf-8-sig"
) as csvfile:

    writer = csv.writer(
        csvfile,
        delimiter=";"
    )

    writer.writerow([
        "File",
        "Status",
        "Message"
    ])

    writer.writerows(report)

# =========================================================
# Summary
# =========================================================

elapsed = time.time() - start_time

average = elapsed / len(rows) if rows else 0

print()
print(LINE)
print("AUTO CUTTER FINISHED")
print(LINE)
print()

print(f"Processed : {len(rows)}")
print(f"Created   : {created}")
print(f"Skipped   : {skipped}")
print(f"Errors    : {errors}")
print()

total_removed = (
    total_intro_removed +
    total_outro_removed
)

print(
    f"Intro Removed : "
    f"{format_time(total_intro_removed)}"
)

print(
    f"Outro Removed : "
    f"{format_time(total_outro_removed)}"
)

print(
    f"Total Removed : "
    f"{format_time(total_removed)}"
)

print()

print(f"Elapsed   : {format_time(elapsed)}")
print(f"Average   : {average:.2f} sec/file")
print()

print(f"Music Root   : {music_root}")
print(f"Output Folder: {output_root}")
print(f"Report       : {report_file}")
print()

if errors == 0:
    print("Everything completed successfully.")
else:
    print("Finished with errors.")

print()
print(LINE)

sys.exit(0)